"""initial migration

Revision ID: e86ae3bc209f
Revises: fc8b1f280fac
Create Date: 2024-09-10 16:51:18.323373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86ae3bc209f'
down_revision = 'fc8b1f280fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
