DEFAULT_INVESTMENT_AMOUNT = 0

MIN_NAME_LENGTH = 1
MAX_NAME_LENGTH = 100

MIN_DESCRIPTION_LENGTH = 1

MINIMUM_PASSWORD_LENGTH = 3

BAD_REQUEST_CODE = 400
METHOD_NOT_ALLOWED_CODE = 405
PAGE_NOT_FOUND_CODE = 404
UNPROCESSABLE_ENTITY = 422

PROJECT_LIFETIME = 3600

COLUMN_NUMBER = 11
ROW_NUMBER = 100
SHEET_ID_NUMBER = 0
